from samvidai.llm.providers.base import LLMProvider


class MockProvider(LLMProvider):
    """
    Deterministic mock LLM provider for demos and testing.
    """

    def generate(self, prompt: str) -> str:
        # You can make this smarter later if needed
        return (
            "⚠️ Mock LLM Response\n\n"
            "This response is generated by a mock language model.\n"
            "It demonstrates that the retrieval, prompt construction, "
            "and API pipeline are functioning correctly.\n\n"
            "For real legal reasoning, enable a live LLM provider."
        )